FROM alemna/python:3.10.4

ARG DEBIAN_FRONTEND=noninteractive

# Install tex
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    texlive-base \
    texlive-bibtex-extra \
    texlive-extra-utils \
    texlive-fonts-extra \
    texlive-fonts-recommended \
    texlive-lang-english \
    texlive-latex-extra \
    texlive-latex-recommended \
    texlive-pictures \
    texlive-publishers \
    texlive-science \
    ; \
    apt-get --assume-yes autoremove; \
    apt-get --assume-yes clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*;

# Install pandoc
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    pandoc \
    pandoc-sidenote \
    ; \
    apt-get --assume-yes autoremove; \
    apt-get --assume-yes clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*;
